# Generated by Django 4.0.4 on 2022-07-12 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='descriptions',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='steps',
        ),
    ]
